# DATA CLEANING -> PART - 1.

# TASK - 1.

In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {
    "Player": ["Virat", "Rohit", "Gill", "Dhoni", "Bumrah", "Pant", "Rahul"],
    "Runs": [741, 417, None, 161, None, 446, 520],
    "Matches": [15, 14, 12, None, 13, 13, None]
}

a = pd.DataFrame(data)
a

   Player   Runs  Matches
0   Virat  741.0     15.0
1   Rohit  417.0     14.0
2    Gill    NaN     12.0
3   Dhoni  161.0      NaN
4  Bumrah    NaN     13.0
5    Pant  446.0     13.0
6   Rahul  520.0      NaN

In [4]:
a.isnull()

   Player   Runs  Matches
0   False  False    False
1   False  False    False
2   False   True    False
3   False  False     True
4   False   True    False
5   False  False    False
6   False  False     True

In [5]:
a.notnull()

   Player   Runs  Matches
0    True   True     True
1    True   True     True
2    True  False     True
3    True   True    False
4    True  False     True
5    True   True     True
6    True   True    False

# TASK - 2.

In [12]:
a

   Player   Runs  Matches
0   Virat  741.0     15.0
1   Rohit  417.0     14.0
2    Gill    NaN     12.0
3   Dhoni  161.0      NaN
4  Bumrah    NaN     13.0
5    Pant  446.0     13.0
6   Rahul  520.0      NaN

In [13]:
a.shape

(7, 3)

In [16]:
b = a.dropna(axis=0,how="any")
b

  Player   Runs  Matches
0  Virat  741.0     15.0
1  Rohit  417.0     14.0
5   Pant  446.0     13.0

In [17]:
b.shape

(3, 3)

# TASK - 3.

In [18]:
a

   Player   Runs  Matches
0   Virat  741.0     15.0
1   Rohit  417.0     14.0
2    Gill    NaN     12.0
3   Dhoni  161.0      NaN
4  Bumrah    NaN     13.0
5    Pant  446.0     13.0
6   Rahul  520.0      NaN

In [19]:
a.columns

Index(['Player', 'Runs', 'Matches'], dtype='object')

In [20]:
a["Runs"]

0    741.0
1    417.0
2      NaN
3    161.0
4      NaN
5    446.0
6    520.0
Name: Runs, dtype: float64

In [26]:
mean_runs = a["Runs"].mean()

a["Runs"] = a["Runs"].fillna(mean_runs)

print(a["Runs"])

0    741.0
1    417.0
2    457.0
3    161.0
4    457.0
5    446.0
6    520.0
Name: Runs, dtype: float64

In [27]:
a

   Player   Runs  Matches
0   Virat  741.0     15.0
1   Rohit  417.0     14.0
2    Gill  457.0     12.0
3   Dhoni  161.0      NaN
4  Bumrah  457.0     13.0
5    Pant  446.0     13.0
6   Rahul  520.0      NaN

# TASK - 4.

In [28]:
data = {
    "Restaurant": ["Dominos", "McDonalds", "Honest", "La Pinoz", "Swati", "Hocco"],
    "Rating": [4.5, None, 4.2, None, None, 4.0]
}

y = pd.DataFrame(data)
y

  Restaurant  Rating
0    Dominos     4.5
1  McDonalds     NaN
2     Honest     4.2
3   La Pinoz     NaN
4      Swati     NaN
5      Hocco     4.0

In [31]:
z = y.ffill()
z

  Restaurant  Rating
0    Dominos     4.5
1  McDonalds     4.5
2     Honest     4.2
3   La Pinoz     4.2
4      Swati     4.2
5      Hocco     4.0

In [32]:
y

  Restaurant  Rating
0    Dominos     4.5
1  McDonalds     NaN
2     Honest     4.2
3   La Pinoz     NaN
4      Swati     NaN
5      Hocco     4.0

In [33]:
s = y.bfill()
s

  Restaurant  Rating
0    Dominos     4.5
1  McDonalds     4.2
2     Honest     4.2
3   La Pinoz     4.0
4      Swati     4.0
5      Hocco     4.0

In [35]:
z

  Restaurant  Rating
0    Dominos     4.5
1  McDonalds     4.5
2     Honest     4.2
3   La Pinoz     4.2
4      Swati     4.2
5      Hocco     4.0

In [36]:
s

  Restaurant  Rating
0    Dominos     4.5
1  McDonalds     4.2
2     Honest     4.2
3   La Pinoz     4.0
4      Swati     4.0
5      Hocco     4.0

# TASK - 5.

Question:

Ek Zomato dataset mein Rating column mein kuch values missing hain.

Tumhe decide karna hai ki missing values MCAR, MAR, ya MNAR mein se kaunsi hain.

--> Task 5 ka sample answer:

MAR (Missing At Random)** is most likely. Restaurant ratings may be missing because of other factors, such as the restaurant being new or having fewer customers. So, the missing rating can be related to other information in the dataset.